#!/bin/bash
# Build the complete reading draft site
# Works locally and in CI/CD (Vercel, Netlify, GitHub Pages)
# Usage: ./build.sh

set -e
REPO="$(cd "$(dirname "$0")" && pwd)"
cd "$REPO"

echo "📚 Syncing chapter files..."

# Freedom Paradox (16 chapters + epilogue)
cp books/freedom-paradox/chapters/ch*.md src/freedom-paradox/
cp books/freedom-paradox/chapters/epilogue.md src/freedom-paradox/ 2>/dev/null || true

# Grammars of the Living World (10 chapters)
cp books/grammars-of-the-living-world/chapters/ch01-the-biological-hypothesis.md src/grammars/
cp books/grammars-of-the-living-world/chapters/ch02-why-stories.md src/grammars/
cp books/grammars-of-the-living-world/chapters/ch03-when-stories-lose-their-homes.md src/grammars/
cp books/grammars-of-the-living-world/chapters/ch04-the-degradation-of-the-hearth.md src/grammars/
cp books/grammars-of-the-living-world/chapters/ch05-the-polarization-of-the-polis.md src/grammars/
cp books/grammars-of-the-living-world/chapters/ch06-machines-for-constructing-stories.md src/grammars/
cp books/grammars-of-the-living-world/chapters/ch07-survival-and-capture.md src/grammars/
cp books/grammars-of-the-living-world/chapters/ch08-the-species-that-got-fire.md src/grammars/
cp books/grammars-of-the-living-world/chapters/ch09-the-trap-of-solving.md src/grammars/
cp books/grammars-of-the-living-world/chapters/ch10-grammars-of-the-living-world.md src/grammars/

# Species That Tells Stories (intro + 5 chapters + conclusion)
cp books/species-that-tells-stories/chapters/intro-the-species-that-got-fire.md src/species-tells-stories/
cp books/species-that-tells-stories/chapters/ch01-the-oldest-technology.md src/species-tells-stories/
cp books/species-that-tells-stories/chapters/ch02-the-darkness-is-the-medicine.md src/species-tells-stories/
cp books/species-that-tells-stories/chapters/ch03-what-the-old-stories-knew.md src/species-tells-stories/
cp books/species-that-tells-stories/chapters/ch04-the-species-in-overshoot.md src/species-tells-stories/
cp books/species-that-tells-stories/chapters/ch05-collaboration-runs-deeper.md src/species-tells-stories/
cp books/species-that-tells-stories/chapters/conclusion-grammars-are-responsibility-structures.md src/species-tells-stories/

# Working Architecture (12 chapters)
cp books/working-architecture/chapters/ch*.md src/working-architecture/

# The Axiom Beneath the Ground
mkdir -p src/axiom
cp books/axiom-beneath-the-ground/chapters/ch*.md src/axiom/

# Fire and Intelligence (12 chapters)
mkdir -p src/fire-and-intelligence
cp books/fire-and-intelligence/chapters/ch*.md src/fire-and-intelligence/

# The Real Cost of Lunch (20 chapters)
mkdir -p src/real-cost-of-lunch
cp books/real-cost-of-lunch/chapters/ch*.md src/real-cost-of-lunch/

# Charts (generated by generate-charts.py)
if [ -d models/charts ]; then
  mkdir -p src/images
  cp models/charts/*.png src/images/ 2>/dev/null || true
fi

echo "🔨 Building mdbook..."
.mdbook-bin/mdbook.exe build

# Copy CNAME for GitHub Pages custom domain
cp CNAME book/ 2>/dev/null || true

echo "✅ Done! Output in book/"
echo "   Open: book/index.html"
