#!/bin/bash
# Build the consolidated book site
# Works locally and in CI/CD (Vercel, Netlify, GitHub Pages)
# Usage: ./build.sh

set -e
REPO="$(cd "$(dirname "$0")" && pwd)"
cd "$REPO"

echo "📚 Syncing chapter files..."

# The Species That Got Fire (consolidated book — 33 chapters)
mkdir -p src/consolidated
cp books/consolidated/chapters/ch*.md src/consolidated/

# The Real Cost of Lunch (standalone companion — 20 chapters)
mkdir -p src/real-cost-of-lunch
cp books/real-cost-of-lunch/chapters/ch*.md src/real-cost-of-lunch/

# The Axiom Beneath the Ground v2 (4 chapters + The Ceremony)
mkdir -p src/axiom-v2
cp books/axiom-beneath-the-ground/chapters/v2-ch*.md src/axiom-v2/
cp books/axiom-beneath-the-ground/chapters/the-ceremony.md src/axiom-v2/

# The Axiom Beneath the Ground v3 — Kundera-style (7 chapters + The Ceremony)
mkdir -p src/axiom-v3
cp books/axiom-beneath-the-ground/chapters/v3/*.md src/axiom-v3/
cp books/axiom-beneath-the-ground/chapters/the-ceremony.md src/axiom-v3/

# The Axiom Beneath the Ground v5 — latest (memoir threads + Whitman/Harris/Ghost/Gita)
# 14 chapters including interludes ch01a and ch04a. BUILD-NOTES.md excluded below.
mkdir -p src/axiom-v5
cp books/axiom-beneath-the-ground/chapters/v5/ch*.md src/axiom-v5/

# Standalone books: Freedom Paradox, Working Architecture, Fire and Intelligence
mkdir -p src/freedom-paradox src/working-architecture src/fire-and-intelligence
cp books/freedom-paradox/chapters/ch*.md src/freedom-paradox/
cp books/working-architecture/chapters/ch*.md src/working-architecture/
cp books/fire-and-intelligence/chapters/ch*.md src/fire-and-intelligence/

# Charts (generated by generate-charts.py)
if [ -d models/charts ]; then
  mkdir -p src/images
  cp models/charts/*.png src/images/ 2>/dev/null || true
fi

echo "🔨 Building mdbook..."
.mdbook-bin/mdbook.exe build

# Copy CNAME for GitHub Pages custom domain
cp CNAME book/ 2>/dev/null || true

echo "✅ Done! Output in book/"
echo "   Open: book/index.html"
