#!/bin/bash
# Build the complete reading draft site
# Works locally and in CI/CD (Vercel, Netlify, GitHub Pages)
# Usage: ./build.sh

set -e
REPO="$(cd "$(dirname "$0")" && pwd)"
cd "$REPO"

echo "📚 Syncing chapter files..."

# Freedom Paradox (16 chapters)
cp books/freedom-paradox/chapters/ch*.md src/freedom-paradox/

# Grammars of the Living World (10 chapters + new Species chapters share the dir)
cp books/grammars-of-the-living-world/chapters/ch01-the-biological-hypothesis.md src/grammars/
cp books/grammars-of-the-living-world/chapters/ch02-why-stories.md src/grammars/
cp books/grammars-of-the-living-world/chapters/ch03-when-stories-lose-their-homes.md src/grammars/
cp books/grammars-of-the-living-world/chapters/ch04-the-degradation-of-the-hearth.md src/grammars/
cp books/grammars-of-the-living-world/chapters/ch05-the-polarization-of-the-polis.md src/grammars/
cp books/grammars-of-the-living-world/chapters/ch06-machines-for-constructing-stories.md src/grammars/
cp books/grammars-of-the-living-world/chapters/ch07-survival-and-capture.md src/grammars/
cp books/grammars-of-the-living-world/chapters/ch08-the-species-that-got-fire.md src/grammars/
cp books/grammars-of-the-living-world/chapters/ch09-the-trap-of-solving.md src/grammars/
cp books/grammars-of-the-living-world/chapters/ch10-grammars-of-the-living-world.md src/grammars/

# Species That Tells Stories (3 chapters so far)
cp books/grammars-of-the-living-world/chapters/ch01-the-oldest-technology.md src/species-tells-stories/
cp books/grammars-of-the-living-world/chapters/ch02-the-darkness-is-the-medicine.md src/species-tells-stories/
cp books/grammars-of-the-living-world/chapters/ch03-what-the-old-stories-knew.md src/species-tells-stories/

# Working Architecture (12 chapters)
cp books/working-architecture/chapters/ch*.md src/working-architecture/

# Charts (generated by generate-charts.py)
if [ -d models/charts ]; then
  cp models/charts/*.png src/images/ 2>/dev/null || true
fi

echo "🔨 Building mdbook..."
.mdbook-bin/mdbook.exe build

echo "✅ Done! Output in book/"
echo "   Open: book/index.html"
