# When "chaos" is actually order: sacred traditions, invisible labor, and who gets to name the body's work

The rhythm Gabrielle Roth called "Chaos" — the wild, head-shaking, full-body-release third movement of her 5Rhythms practice — draws directly from Yoruba sacred drumming traditions, one of the most mathematically precise and spiritually structured musical systems on Earth. That a Western practitioner extracted this tradition, stripped its cosmological framework, and labeled it "chaos" replicates a colonial logic so deeply embedded it has largely gone unexamined within the 5Rhythms community. This same pattern — embodied traditions extracted, decontextualized, renamed, and economically reorganized to benefit those doing the naming — threads through the gender dynamics at Esalen Institute, the exploitation Degas documented in Parisian ballet, and the biomechanics of high heels. Across all four domains, the through-line is the same: **someone's disciplined, sacred, or painful physical labor is made to appear natural, primitive, effortless, or invisible — and the person doing that labor is not the person who profits.**

---

## Babatunde Olatunji's drumming became Roth's "chaos"

The specific musician at the center of the 5Rhythms–Yoruba connection is **Babatunde Olatunji** (1927–2003), the Nigerian master percussionist whose 1960 album *Drums of Passion* — a collection of Yoruba rhythms — sold over five million copies and fundamentally reshaped American audiences' encounter with African music. Olatunji taught at both Esalen Institute and the Omega Institute for Holistic Studies, the same institutions where Roth developed and taught her practice. Liner notes for the Time Capsule Records compilation of Roth's work describe how "as the 'world music' phenomenon unfolded around him, **Olatunji passed into Roth's sphere**, teaching at both Esalen and the Omega Institute in New York City."

The pipeline was not indirect. Two of Olatunji's protégés — **Gordy Ryan** and **Sanga of the Valley** (Anthony Francis), both of whom toured with Olatunji's "Drums of Passion" ensemble — became the only fixed percussionists in Gabrielle Roth & The Mirrors, her musical ensemble. Sanga spent 25 years as one of Olatunji's lead djembe players and is currently described on Esalen's website as "a master drummer and living embodiment of the 5Rhythms cosmology." Roth's husband Robert Ansell played instruments explicitly including **"Yoruba and Igbo batá"** drums, alongside ashiko, dun-dun, and djembe. Esalen's own newsletter pairs them directly: "Gabrielle Roth's ecstatic dance and Babatunde Olatunji's drumming sessions used movement and rhythm to create connections and unfold epiphanies."

Roth's pivotal encounter with live drumming at Esalen became her origin story. Live percussionists "were pounding out rhythms so irresistible Roth found herself on the dance floor in spite of her knee," she later recalled. She danced until she "disappeared inside the dance" and entered "another universe, shifted into a new dimension in which there were no boundaries." This transformative experience — almost certainly involving drummers trained in or influenced by Yoruba percussion traditions — became the foundation for her entire practice. In *Maps to Ecstasy* (1989), she made the connection explicit: **"To move into chaos, I love to be carried away by tribal drumming."**

The practice is formally described as having roots in "Native American shamanic traditions, Afro-Brazilian Candomblé and Yoruba drumming." Roth called herself an "urban shaman" and described 5Rhythms as "a body of work born in the sixties that is at least seventy-five thousand years old" — a claim that simultaneously acknowledges ancient origins and erases specific cultural ownership.

---

## What Yoruba drumming actually is — and why "chaos" inverts its meaning

In Yoruba cosmology, the drum is not an instrument. It is a deity. **Àyàn** (known as Añá in Cuba) is the Yoruba òrìṣà of drumming itself — "the spirit of the wood," whose presence is required wherever drumming for the orishas occurs. The Ile Oro Yoruba cultural organization states plainly: "For the Yorùbá, the drum is the heartbeat of the culture — a sacred pulse that connects humanity to divinity and binds the community together."

The **batá drums** — a set of three hourglass-shaped drums called Iyá (mother), Itótele (father), and Okónkolo (baby) — are the principal instruments of **Ṣàngó** worship, the thunder deity. Sacred batá are believed to contain the spiritual force required to summon orishas into ceremony. The **dùndún** (talking drums) literally speak the Yoruba language through pitch modulation, their tonal contours reproducing the speech patterns of a tonal language. Each orisha has specific rhythms, colors, and dance patterns — nothing is improvised, nothing is random. As Ayodeji Ogunnaike of Harvard's Center for the Study of World Religions explains, Yoruba tradition "categorically resists the Cartesian dualism between body and mind," and the drums, rhythms, and body movements associated with Ṣàngó "all produce, channel, and evoke a type of rapid and boisterous energy linked with Ṣàngó's nature as thunder and lightning."

The mathematical sophistication is extraordinary. Yoruba drumming operates through **polyrhythmic structures** — 3:2 and 3:4 cross-rhythms interlocking in precise ratios, anchored by a seven-stroke bell pattern (the clave) that serves as the foundational timeline. As Matthew Montfort notes, "While European classical music has developed complex harmonies of tones, West African music has developed a complex interweaving of contrasting rhythmic patterns." This is, by any measure, one of the most structurally complex musical traditions humans have created — the polar opposite of disorder.

The label "Chaos" thus performs a specific colonial inversion. Yoruba drumming is highly structured; it is called chaotic. It is sacred communication with specific deities; it is reduced to soundtrack for personal catharsis. It is hereditary knowledge transmitted through generations of master drummers; it is appropriated without cultural context. It represents mathematical precision; it is named for its supposed absence of pattern. The Smithsonian Folkways describes Yoruba drumming as "overlapping rhythms embedded with symbolic religious meanings" — but in Roth's framework, this tradition became the music you "surrender" to, where you "let go of the head" and "move faster than you can think."

---

## The critique that hasn't yet found its name

A striking finding of this research is that **no specific published critique by a named Black practitioner or scholar directly targets the naming of the "Chaos" rhythm as racist.** This does not mean the argument lacks force — the structural evidence is overwhelming — but rather that the critique exists primarily in oral traditions, workshop conversations, and social media spaces not indexed by search engines. The 5Rhythms community is predominantly white and middle-class, which may explain why this conversation has not surfaced with the intensity it has in yoga (where Susanna Barkataki and others have built extensive decolonization frameworks) or mindfulness (where Ronald Purser's "McMindfulness" critique and the "May We Gather" movement have gained significant traction).

Adjacent critiques, however, are substantial. **Tada Hozumi**, a cultural somatics practitioner, wrote an open letter arguing that the entire field of somatics is structurally racist because it involves white practitioners appropriating practices from non-white cultures. **Beth McNamara** described ecstatic dance festivals as "spiritual settler colonialism" in her 2020 essay "Ecstatic Colonization." The Dancegeist article "Reform in Somatics" states bluntly: "Somatic practices have been named, packaged, marketed, certified, and often taught by folks who look like me. However, these practices have been created by Asian, African and Indigenous folks, and those roots need to be honored." **Resmaa Menakem**, author of *My Grandmother's Hands*, has developed "Somatic Abolitionism," framing cultural appropriation as a behavior arising from "anxious cultural attachment."

A 2025 academic article in the *Journal of Contemporary Religion* studying 5Rhythms in Australia includes a revealing footnote: "We acknowledge that 'tribe' can be a problematic term with regard to misleading cultural stereotypes and cultural appropriation of Indigenous traditions. Roth also problematically used the term 'tribe' to describe the 5Rhythms community." Perhaps most telling is one practitioner's casual description of the Chaos portion of class: **"This is the 'voo-doo rain dance' portion of the class, when eyes roll into the back of the head, ponytails are released and hair let down, flailing and spinning and wild hypnotic movement ensues."** That a participant would unselfconsciously describe African-derived sacred music practice as "voo-doo rain dance" reveals exactly how the "Chaos" label functions — it provides permission to experience Yoruba-rooted musical traditions through the lens of primitivism and loss of control.

The 5Rhythms organization, now led by Roth's son Jonathan Horan, has issued no formal statement on cultural appropriation. No discussion of renaming has been publicly documented. The organization's materials continue to use terms like "tribal drumming," "urban shaman," "Medicine Mandala," and "dojo of the body" — borrowing from Japanese, Native American, and other non-Western traditions without attribution.

---

## Five rhythms, five traditions, one pattern of extraction

Each of the 5Rhythms draws from specific non-Western traditions, though the sourcing is usually obscured behind universalist language about "natural movement patterns." Roth's correspondence system — what she called the "Medicine Mandala" — maps each rhythm onto an emotion, element, life stage, and archetype:

**Flowing** (fear, earth, birth/infancy) involves smooth, continuous, circular, receptive movements. Its qualities strongly echo **tai chi** and water-based movement philosophy, though Roth did not typically cite Chinese traditions. She coded it as "feminine" energy. **Staccato** (anger, fire, childhood) involves percussive, angular, boundary-making movements — described as "karate-like." This draws from **martial arts** and almost certainly from **flamenco**, given Roth's formative encounter with La Chunga, the Spanish Roma dancer she said "ripped me open." **Chaos** (grief/sadness, water, puberty) is the African/Yoruba-derived rhythm discussed above, accompanied by Sufi references — Roth described the dancer in chaos as "a rag-doll dervish." **Lyrical** (joy, air, maturity) is described as "the rhythm of trance and self-realization," drawing on Sufi whirling and ecstatic traditions. **Stillness** (compassion, space/ether, death) draws explicitly on **Zen Buddhism** and meditation traditions — Roth described her practice as "a contemporary Zen shamanic practice" and incorporated Tibetan singing bowls and Buddhist mantras.

The neuroscience offers partial validation of universal movement patterns. Drumming at approximately 7–9 beats per second induces theta brain activity associated with trance states. Dance-induced altered states involve increased blood flow to the cerebellum and insula while the amygdala and frontal cortex receive less — reducing anxiety and dissolving the sense of time. A 2024 fMRI study of Sangoma trance found increased activation in the posterior cingulate cortex and default mode network during music-induced trance. The pattern of building intensity → peak → release → calm appears across many ecstatic traditions worldwide — Haitian Vodou, Korean Salpuri, San healing dances, Sufi Sama, Greek Dionysian ecstasy. **The existence of cross-cultural movement universals is real, but it does not justify the erasure of specific cultural origins.** That humans everywhere dance toward ecstasy does not mean any particular person may rebrand someone else's sacred tradition.

---

## At Esalen, men got the PBS specials while women got $12.50 per massage

The gender dynamics at Esalen Institute map the same pattern onto a different axis. The institute's founding mythology centers on men doing intellectual work — **Michael Murphy** and **Dick Price** (both Stanford-educated) co-founding the institute, **Fritz Perls** running encounter groups, **Abraham Maslow** providing the philosophical framework of self-actualization, **Alan Watts** translating Eastern philosophy, **Joseph Campbell** teaching mythology, **Stanislav Grof** developing transpersonal psychology, **Gregory Bateson** bringing systems theory. These men got book deals, PBS specials, professorships, named academic chairs, and enduring cultural legacies.

The women who made Esalen what it actually *is* — the place people go to be touched, moved, and physically transformed — worked for hourly wages. **Peggy Horan** arrived in 1969, co-created Esalen Massage with Deborah Medow, Brita Ostrom, and Vicki Topp, managed the Healing Arts department for a decade, founded the Esalen Massage School, and after more than 50 years is classified as a "legacy teacher." She recalls: **"Massages cost $15 at the time, of which we got $12.50."** No residuals, no royalties, no platform that outlasts the hour of physical contact.

The economic arithmetic is devastating. Campbell's *The Power of Myth* PBS series (1988) became one of the most watched in public television history. The companion book, edited by Jacqueline Kennedy Onassis, was a national bestseller. His earlier *Hero with a Thousand Faces* directly shaped George Lucas's *Star Wars* — a franchise worth tens of billions. Alan Watts wrote 25 books and had a TV series; his lectures now have hundreds of millions of YouTube views, generating ongoing revenue managed by his son. **Intellectual work generates residual income: royalties compound for decades after death. Bodywork generates only hourly income — when you stop touching, you stop earning.** The work leaves no tangible product.

Two women's stories expose the structural mechanism most clearly. **Charlotte Selver** (1901–2003) led the very first experimental workshop at Esalen in 1963 — before Perls, before anyone else. Her Sensory Awareness work directly influenced Perls, Erich Fromm, and Alan Watts. She held a faculty position at the New School for Social Research. Yet she has no PBS special, no bestselling book, no named chair. Her husband Charles Brooks wrote the book about her method. **Ida Rolf** (1896–1979) held a PhD in biochemistry from Columbia — earned in 1920, making her one of the most credentialed people at Esalen by far. She worked at the Rockefeller Institute. Yet she is remembered as a bodyworker, and her systematic intellectual work was reduced to the colloquialism "Rolfing" — a nickname she disliked. Meanwhile, male intellectuals retained the formal framing of their contributions: "Gestalt therapy," "humanistic psychology," "comparative mythology."

Jeffrey Kripal's 594-page *Esalen: America and the Religion of No Religion* (2007), the definitive institutional history, reproduces the hierarchy it could have analyzed. Multiple reviewers note the absence of critical gender analysis and the overwhelming focus on male thinkers. The book's index is dominated by male names. The very act of writing the history recapitulates the pattern: "real" history is about ideas (male); the body (female) is backdrop.

---

## Degas was not celebrating beauty — he was documenting a marketplace

The common museum interpretation of Edgar Degas's ballet paintings — beautiful dancers, celebration of grace, masterful capture of movement — is historically illiterate. Degas was painting the **Paris Opéra ballet as a system of institutionalized sexual exploitation**, and art historians have spent decades trying to make this clear.

The *petits rats* ("little rats") were working-class girls, some as young as ten, recruited into the Paris Opéra. They worked six days a week for minimal pay. Louis Véron, appointed Opera administrator around 1830, deliberately **decreased dancers' wages to force them to seek wealthy protectors** — institutionalizing prostitution as economic policy. The *foyer de la danse*, a lavish salon directly behind the stage, was architecturally designed as a men's club where wealthy subscribers (*abonnés*) could proposition dancers. When Charles Garnier built the Palais Garnier, he included a separate entrance for these men and designed the foyer explicitly for their access. Mothers frequently brokered arrangements for their daughters. As historian Lorraine Coons documented, even successful dancers who avoided prostitution were assumed to engage in it. A former dancer reportedly stated: "As soon as she enters the Opéra her destiny as a whore is sealed."

Degas's canvases are full of evidence. In *L'Étoile* (1878), a man in a black tuxedo lurks in the wings behind the curtsying dancer — the abonné made visible. In *The Rehearsal of the Ballet Onstage* (1874), two dark-suited men sit watching rehearsal from positions of comfort and power. His **Cardinal Monotypes** (c.1876–1880s) — approximately 40 prints illustrating his friend Ludovic Halévy's novels — make the ballet-prostitution connection completely explicit, depicting a stage mother selling her two dancing daughters. His *Little Dancer Aged Fourteen* (1881), a wax sculpture of **Marie van Goethem**, depicted a real girl whose mother was a laundress and likely prostitute, whose older sister was a sex worker. Critics called Marie "monkey-like" and said her face bore "the hateful promise of every vice." She was dismissed from the Opéra in 1882 and likely returned to sex work. The sculpture that immortalized her exploitation had no buyers in Degas's lifetime; in 2015 it was valued at approximately **$23 million**.

Feminist art historian **Eunice Lipton** (*Looking into Degas*, 1986) demonstrated that these paintings "actively carry and create meaning" about class, sex, and labor. **Jill DeVonyar** and **Richard Kendall** (*Degas and the Dance*, 2002) described the foyer de la danse as "a hunting ground where the predators/abonnés circle around the gazelles/ballerinas." Backstage access for abonnés was not banned until 1927 — to "howls of outrage."

Degas himself is not innocent in this. He said, "I have perhaps too often considered woman as an animal." Some accounts indicate he became an abonné himself. His paintings oscillate between documentation and complicity, between exposing a system and participating in the voyeurism that sustained it.

---

## Effortless effort as a technology of erasure

Ballet's central aesthetic demand — that extreme physical labor appear weightless and natural — connects directly to **sprezzatura**, the Renaissance concept coined by Baldassare Castiglione in 1528: "a certain nonchalance which conceals all artistry and makes whatever one says or does seem uncontrived and effortless." When applied to female bodies in ballet, this aesthetic becomes a technology for making women's labor invisible.

**Chloe Angyal** (*Turning Pointe*, 2021) identified the connection precisely. She recognized that what Duke University researchers in 2003 called "effortless perfection" — gendered expectations requiring young women to succeed at everything while appearing not to try — "is just ballet. This is what we were taught in dance: to be athlete-strong but artist-unruffled. **To work just as hard at concealing the work as we did at the work itself.**" Edward Villella described the ideal: "steel-like legs that are doing the most fantastical feats while the upper body is soft and lovely as though nothing was going on underneath."

The physical costs are staggering. **Fifty percent** of professional ballet dancers develop disordered eating over their lifetimes. Dancers are three times more likely to develop anorexia than non-dancers. Pointe shoes — worn exclusively by women — bear the full body weight on a tiny area, causing documented injuries, chronic pain, and long-term musculoskeletal damage. A 2023 study found ballet institutions actively teach dancers to "normalise physical pain." Training totals 20–39 hours per week. Women have greater injury prevalence than men due to higher technical requirements, while **72% of artistic directors are men** and 81% of the world's most prestigious companies are led by men. In 2016, New York City Ballet performed 58 ballets — not one choreographed by a woman.

High heels replicate the same logic. Originating as **Persian cavalry footwear** (functional, masculine, military), heels were adopted by European aristocrats — Louis XIV, only 5'4", made red heels a mark of courtly status. As heels became feminized in the 18th century, they shifted from power symbols to aesthetic constraints. A 2023 systematic review of 33 studies found high heels significantly alter gait, shorten the Achilles tendon, increase back pain, and reduce postural stability. High-heel injuries nearly doubled from 2002 to 2012. Yet 37–69% of women wear them daily. Both ballet and heels began as male domains, were feminized, and in feminization became mechanisms for displaying constraint as elegance.

---

## When does discipline serve the body, and when does it serve power?

**Sandra Lee Bartky** identified the paradox most precisely in her 1988 essay "Foucault, Femininity, and the Modernization of Patriarchal Power": **"While its imposition may promote a larger disempowerment, discipline may bring with it a certain development of a person's powers."** Women "have a stake in the perpetuation of their skills, whatever it may have cost to acquire them." This captures exactly why the question of adaptive versus maladaptive body discipline resists simple answers.

The feminist philosophical tradition offers several frameworks for distinguishing. **Susan Bordo** (*Unbearable Weight*, 1993) argued that the female body is a text inscribed with cultural messages, and that disciplinary practices — diet, exercise, dress — are tools through which bodies are "subconsciously exacted and normalized." Anorexia, she argued, is "a self-defeating form of protest" where the subject questions cultural ideals while being absorbed into self-destruction. **Iris Marion Young** ("Throwing Like a Girl," 1980) showed that feminine movement is characterized by inhibited intentionality — women's bodies are simultaneously subjects acting and objects observed. **Jill Green** applied Foucault's concept of "docile bodies" directly to ballet training, finding that mirrors in dance studios provide "a means for self-surveillance" and arguing for giving "dance students ownership of their bodies."

Five questions emerge from this scholarship for evaluating any body discipline:

- **Who benefits?** Does the practice primarily serve the practitioner's growth, or external structures' profit and aesthetic pleasure?
- **Is consent informed?** Does the practitioner choose the discipline with full knowledge of costs, or is she shaped by economic necessity and social pressure?
- **Is pain normalized or respected?** Pushing through discomfort for mastery differs from institutional demands that treat injury as acceptable cost.
- **Is labor concealed or transcended?** Making effort invisible to serve others' comfort differs from genuine ease achieved through mastery.
- **Who controls the narrative?** Does the practitioner name her own experience, or does someone else label her tradition — as, say, "chaos"?

---

## What respectful integration might look like

The yoga decolonization movement offers the most developed models. Susanna Barkataki (*Embrace Yoga's Roots*) proposes five steps: practice self-inquiry, learn and cite cultural references correctly, ask hard questions about accessibility, study beyond surface techniques, and practice humility. The key principle across yoga, mindfulness, and dance decolonization work is the same: **move from extraction to reciprocity, from consumption to relationship.**

For 5Rhythms specifically, this might mean explicitly acknowledging in teacher training and class settings the Yoruba, Sufi, Buddhist, martial arts, and flamenco traditions that inform each rhythm. It would mean retiring language like "tribal drumming" in favor of specific attributions. It would mean elevating teachers and musicians from source cultures, directing revenue toward Yoruba arts organizations, and requiring teacher trainees to study the traditions they draw upon — not just the mechanics of the practice. It would mean telling Roth's actual biographical story — her encounters with La Chunga, the Nigerian National Ballet, Olatunji's students, and specific spiritual traditions — rather than claiming access to "universal" or "primal" rhythms that exist beyond culture.

Whether the word "Chaos" itself should change is perhaps less important than whether the 5Rhythms community can develop the capacity to hold what that word has meant — and hidden. The most sophisticated rhythmic-mathematical tradition on the planet was named for its supposed absence of pattern. Women who created the embodied practices that defined an institution earned $12.50 an hour while men who theorized about consciousness got PBS specials. Fourteen-year-old girls dancing on broken feet were painted as icons of grace. In each case, the mechanism is the same: the labor is real, the suffering is real, the tradition is real — and someone else gets to name it, frame it, and collect the residuals.

I found it — *Big Sur Women* by Judith Goodman and Pat Addleman, published in 1985 by Big Sur Women Press. It's a compilation of interviews, diaries, poetry, and photographs by and about 19 Big Sur women, from early pioneer days up to when the book was published. Goodman, a Berkeley housewife who moved to Big Sur, became fascinated with the solitary, harsh way of life of the area's women and set about compiling their narratives — names like Grace Boronda, Julia Pfeiffer Burns, Elfrieda Hayes, Lillian Bos Ross, Rosa Nash. It's described as the result of her personal quest for balance between solitude and community involvement.

This is a pioneer women's oral history book, not specifically about Esalen women — but the resonance is powerful. Big Sur's women were already invisible *before* Esalen arrived on their land. The pattern predates the institution.

As for other angles I think the report missed or underplayed:

**The sexual economy at Esalen specifically.** Fritz Perls was notorious for sexually exploiting workshop participants — he openly propositioned women in encounter groups, and this was framed as "therapeutic confrontation" rather than harassment. The encounter group format itself normalized male aggression as "authenticity" and "breaking through." This is a dimension the report barely touches: it wasn't just that women's intellectual work was devalued — the institutional culture actively sexualized them while they were trying to work.

**The lineage theft pattern in somatics more broadly.** Charlotte Selver's teacher was **Elsa Gindler** in Berlin, whose work also deeply influenced Moshe Feldenkrais. The transmission line goes: Gindler (woman) → Selver (woman, brought it to the U.S.) → male practitioners who got the credit and built named methods. This is a repeating structure.

**Roth's own navigation of gendered power.** She arrived at Esalen in the late 1960s, initially working with children and psychiatric patients in the theater program — not the high-status encounter groups. Her trajectory from theater teacher to "urban shaman" involved claiming spiritual authority in a way that required borrowing from traditions (shamanism, Yoruba, Sufi) that lent her work gravitas the institution wouldn't grant to a woman's dance practice on its own terms.

**The Lucia Horan thread** — Peggy Horan's daughter, born at Esalen in 1976, now teaches 5Rhythms *and* Esalen massage *and* dharma — she literally embodies the second-generation fusion of the women's lineages. That's a living bridge between Peggy's bodywork and Roth's movement work.

**The strongest angle I didn't develop for the book's argument:** How all of this maps onto your Prometheus/fire framework. The human potential movement *is* the Prometheus story in miniature — power (consciousness techniques, altered states, somatic technologies) acquired without the responsibility structures (cultural context, ethical containers, economic justice) to hold it. Esalen took fire from Yoruba drummers, Japanese Zen, Indian yoga, and gave it to California seekers without the grammars. The gender piece is that women were expected to *be* the container (the body, the massage, the holding) while men got to *be* the fire (the ideas, the breakthroughs, the fame).

That last angle feels like where this connects most directly to *The Species That Got Fire.* Want me to develop any of these threads further?